name: Update Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'docker/**'

env:
  PROJECT_NAME: gmod-builder # Dockerhub project

jobs:
  build_push_panel:
    name: Build and Push Container
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:latest"