name: Build & Release Template

on: 
  push:
    paths:
      - 'source/**'
      - 'premake5.lua'
      - '.github/workflows/compile-release.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build-release:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile-release.yml@workflow
    permissions:
      contents: write
    with:
      PROJECT_NAME: "template"
      BUILD_64x: "true"
      REALM: "sv"
      ARTIFACT_EXPIRE: "1"
      RELEASE_DRAFT: true