name: Build

on: [push, pull_request, workflow_dispatch]
  
env:
  PROJECT_NAME: "template"
  BUILD_64x: "false"
  REALM: "sv"
  FINAL_REALM: "sv"

jobs:
  build:
    uses: RaphaelIT7/gmodcommon-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "template"
      BUILD_64x: "false"
      REALM: "sv"
      FINAL_REALM: "sv"