name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "template"
      BUILD_64x: "true"
      REALM: "sv"
      ARTIFACT_EXPIRE: "1"
  
  release:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/release.yml@workflow
    with:
      PROJECT_NAME: "template"
      BUILD_64x: "true"
      REALM: "sv"
      RELEASE: true
      RELEASE_DRAFT: true